//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crusaders
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamesResult
    {
        public GamesResult()
        {
            this.Games = new HashSet<Game>();
        }
    
        public int id { get; set; }
        public string Result { get; set; }
        public string Opponent { get; set; }
        public string Venue { get; set; }
        public string Comp { get; set; }
        public string Data { get; set; }
    
        public virtual ICollection<Game> Games { get; set; }
    }
}
