//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crusaders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.Games = new HashSet<Game>();
        }
    
        public int id { get; set; }
        public string Number { get; set; }
        public string FamilyName { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string Avatar { get; set; }
    
        public virtual ICollection<Game> Games { get; set; }
    }
}
