//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 22/07/2015 22:21:10
namespace Crusaders.CrusadersService
{
    
    /// <summary>
    /// There are no comments for CrusadersEntities in the schema.
    /// </summary>
    public partial class CrusadersEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new CrusadersEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public CrusadersEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("CrusadersModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("Crusaders.CrusadersService", typeName.Substring(14)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Crusaders.CrusadersService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("CrusadersModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Games1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Game> Games1
        {
            get
            {
                if ((this._Games1 == null))
                {
                    this._Games1 = base.CreateQuery<Game>("Games1");
                }
                return this._Games1;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Game> _Games1;
        /// <summary>
        /// There are no comments for GameResults in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<GameResult> GameResults
        {
            get
            {
                if ((this._GameResults == null))
                {
                    this._GameResults = base.CreateQuery<GameResult>("GameResults");
                }
                return this._GameResults;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<GameResult> _GameResults;
        /// <summary>
        /// There are no comments for Players in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Player> Players
        {
            get
            {
                if ((this._Players == null))
                {
                    this._Players = base.CreateQuery<Player>("Players");
                }
                return this._Players;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Player> _Players;
        /// <summary>
        /// There are no comments for Tickets in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Ticket> Tickets
        {
            get
            {
                if ((this._Tickets == null))
                {
                    this._Tickets = base.CreateQuery<Ticket>("Tickets");
                }
                return this._Tickets;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Ticket> _Tickets;
        /// <summary>
        /// There are no comments for NewsEntities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<NewsEntity> NewsEntities
        {
            get
            {
                if ((this._NewsEntities == null))
                {
                    this._NewsEntities = base.CreateQuery<NewsEntity>("NewsEntities");
                }
                return this._NewsEntities;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<NewsEntity> _NewsEntities;
        /// <summary>
        /// There are no comments for Games1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToGames1(Game game)
        {
            base.AddObject("Games1", game);
        }
        /// <summary>
        /// There are no comments for GameResults in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToGameResults(GameResult gameResult)
        {
            base.AddObject("GameResults", gameResult);
        }
        /// <summary>
        /// There are no comments for Players in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPlayers(Player player)
        {
            base.AddObject("Players", player);
        }
        /// <summary>
        /// There are no comments for Tickets in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTickets(Ticket ticket)
        {
            base.AddObject("Tickets", ticket);
        }
        /// <summary>
        /// There are no comments for NewsEntities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToNewsEntities(NewsEntity newsEntity)
        {
            base.AddObject("NewsEntities", newsEntity);
        }
    }
    /// <summary>
    /// There are no comments for CrusadersModel.Game in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class Game
    {
        /// <summary>
        /// Create a new Game object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        /// <param name="opponent">Initial value of Opponent.</param>
        /// <param name="venue">Initial value of Venue.</param>
        /// <param name="comp">Initial value of Comp.</param>
        /// <param name="data">Initial value of Data.</param>
        /// <param name="image">Initial value of Image.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Game CreateGame(int ID, string opponent, string venue, string comp, string data, string image)
        {
            Game game = new Game();
            game.id = ID;
            game.Opponent = opponent;
            game.Venue = venue;
            game.Comp = comp;
            game.Data = data;
            game.Image = image;
            return game;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property Opponent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Opponent
        {
            get
            {
                return this._Opponent;
            }
            set
            {
                this.OnOpponentChanging(value);
                this._Opponent = value;
                this.OnOpponentChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Opponent;
        partial void OnOpponentChanging(string value);
        partial void OnOpponentChanged();
        /// <summary>
        /// There are no comments for Property Venue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Venue
        {
            get
            {
                return this._Venue;
            }
            set
            {
                this.OnVenueChanging(value);
                this._Venue = value;
                this.OnVenueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Venue;
        partial void OnVenueChanging(string value);
        partial void OnVenueChanged();
        /// <summary>
        /// There are no comments for Property Comp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Comp
        {
            get
            {
                return this._Comp;
            }
            set
            {
                this.OnCompChanging(value);
                this._Comp = value;
                this.OnCompChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Comp;
        partial void OnCompChanging(string value);
        partial void OnCompChanged();
        /// <summary>
        /// There are no comments for Property Data in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Data
        {
            get
            {
                return this._Data;
            }
            set
            {
                this.OnDataChanging(value);
                this._Data = value;
                this.OnDataChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Data;
        partial void OnDataChanging(string value);
        partial void OnDataChanged();
        /// <summary>
        /// There are no comments for Property Image in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Image
        {
            get
            {
                return this._Image;
            }
            set
            {
                this.OnImageChanging(value);
                this._Image = value;
                this.OnImageChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Image;
        partial void OnImageChanging(string value);
        partial void OnImageChanged();
        /// <summary>
        /// There are no comments for Property Result_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Result_id
        {
            get
            {
                return this._Result_id;
            }
            set
            {
                this.OnResult_idChanging(value);
                this._Result_id = value;
                this.OnResult_idChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Result_id;
        partial void OnResult_idChanging(global::System.Nullable<int> value);
        partial void OnResult_idChanged();
        /// <summary>
        /// There are no comments for Property Player_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Player_id
        {
            get
            {
                return this._Player_id;
            }
            set
            {
                this.OnPlayer_idChanging(value);
                this._Player_id = value;
                this.OnPlayer_idChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Player_id;
        partial void OnPlayer_idChanging(global::System.Nullable<int> value);
        partial void OnPlayer_idChanged();
        /// <summary>
        /// There are no comments for Tickets in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Ticket> Tickets
        {
            get
            {
                return this._Tickets;
            }
            set
            {
                if ((value != null))
                {
                    this._Tickets = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Ticket> _Tickets = new global::System.Collections.ObjectModel.Collection<Ticket>();
        /// <summary>
        /// There are no comments for GamesResult in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public GameResult GamesResult
        {
            get
            {
                return this._GamesResult;
            }
            set
            {
                this._GamesResult = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private GameResult _GamesResult;
        /// <summary>
        /// There are no comments for Players in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Player> Players
        {
            get
            {
                return this._Players;
            }
            set
            {
                if ((value != null))
                {
                    this._Players = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Player> _Players = new global::System.Collections.ObjectModel.Collection<Player>();
    }
    /// <summary>
    /// There are no comments for CrusadersModel.GameResult in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class GameResult
    {
        /// <summary>
        /// Create a new GameResult object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        /// <param name="result">Initial value of Result.</param>
        /// <param name="opponent">Initial value of Opponent.</param>
        /// <param name="venue">Initial value of Venue.</param>
        /// <param name="comp">Initial value of Comp.</param>
        /// <param name="data">Initial value of Data.</param>
        /// <param name="points">Initial value of Points.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static GameResult CreateGameResult(int ID, bool result, string opponent, string venue, string comp, string data, string points)
        {
            GameResult gameResult = new GameResult();
            gameResult.id = ID;
            gameResult.Result = result;
            gameResult.Opponent = opponent;
            gameResult.Venue = venue;
            gameResult.Comp = comp;
            gameResult.Data = data;
            gameResult.Points = points;
            return gameResult;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property Result in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Result
        {
            get
            {
                return this._Result;
            }
            set
            {
                this.OnResultChanging(value);
                this._Result = value;
                this.OnResultChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Result;
        partial void OnResultChanging(bool value);
        partial void OnResultChanged();
        /// <summary>
        /// There are no comments for Property Opponent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Opponent
        {
            get
            {
                return this._Opponent;
            }
            set
            {
                this.OnOpponentChanging(value);
                this._Opponent = value;
                this.OnOpponentChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Opponent;
        partial void OnOpponentChanging(string value);
        partial void OnOpponentChanged();
        /// <summary>
        /// There are no comments for Property Venue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Venue
        {
            get
            {
                return this._Venue;
            }
            set
            {
                this.OnVenueChanging(value);
                this._Venue = value;
                this.OnVenueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Venue;
        partial void OnVenueChanging(string value);
        partial void OnVenueChanged();
        /// <summary>
        /// There are no comments for Property Comp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Comp
        {
            get
            {
                return this._Comp;
            }
            set
            {
                this.OnCompChanging(value);
                this._Comp = value;
                this.OnCompChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Comp;
        partial void OnCompChanging(string value);
        partial void OnCompChanged();
        /// <summary>
        /// There are no comments for Property Data in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Data
        {
            get
            {
                return this._Data;
            }
            set
            {
                this.OnDataChanging(value);
                this._Data = value;
                this.OnDataChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Data;
        partial void OnDataChanging(string value);
        partial void OnDataChanged();
        /// <summary>
        /// There are no comments for Property Points in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Points
        {
            get
            {
                return this._Points;
            }
            set
            {
                this.OnPointsChanging(value);
                this._Points = value;
                this.OnPointsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Points;
        partial void OnPointsChanging(string value);
        partial void OnPointsChanged();
        /// <summary>
        /// There are no comments for Game in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Game> Game
        {
            get
            {
                return this._Game;
            }
            set
            {
                if ((value != null))
                {
                    this._Game = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Game> _Game = new global::System.Collections.ObjectModel.Collection<Game>();
    }
    /// <summary>
    /// There are no comments for CrusadersModel.Player in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class Player
    {
        /// <summary>
        /// Create a new Player object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        /// <param name="number">Initial value of Number.</param>
        /// <param name="familyName">Initial value of FamilyName.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="position">Initial value of Position.</param>
        /// <param name="avatar">Initial value of Avatar.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Player CreatePlayer(int ID, string number, string familyName, string name, string position, string avatar)
        {
            Player player = new Player();
            player.id = ID;
            player.Number = number;
            player.FamilyName = familyName;
            player.Name = name;
            player.Position = position;
            player.Avatar = avatar;
            return player;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property Number in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this.OnNumberChanging(value);
                this._Number = value;
                this.OnNumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Number;
        partial void OnNumberChanging(string value);
        partial void OnNumberChanged();
        /// <summary>
        /// There are no comments for Property FamilyName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FamilyName
        {
            get
            {
                return this._FamilyName;
            }
            set
            {
                this.OnFamilyNameChanging(value);
                this._FamilyName = value;
                this.OnFamilyNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FamilyName;
        partial void OnFamilyNameChanging(string value);
        partial void OnFamilyNameChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Position in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Position
        {
            get
            {
                return this._Position;
            }
            set
            {
                this.OnPositionChanging(value);
                this._Position = value;
                this.OnPositionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Position;
        partial void OnPositionChanging(string value);
        partial void OnPositionChanged();
        /// <summary>
        /// There are no comments for Property Avatar in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Avatar
        {
            get
            {
                return this._Avatar;
            }
            set
            {
                this.OnAvatarChanging(value);
                this._Avatar = value;
                this.OnAvatarChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Avatar;
        partial void OnAvatarChanging(string value);
        partial void OnAvatarChanged();
        /// <summary>
        /// There are no comments for Games in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Game> Games
        {
            get
            {
                return this._Games;
            }
            set
            {
                if ((value != null))
                {
                    this._Games = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Game> _Games = new global::System.Collections.ObjectModel.Collection<Game>();
    }
    /// <summary>
    /// There are no comments for CrusadersModel.Ticket in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class Ticket
    {
        /// <summary>
        /// Create a new Ticket object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        /// <param name="price">Initial value of Price.</param>
        /// <param name="description">Initial value of Description.</param>
        /// <param name="type">Initial value of Type.</param>
        /// <param name="ageOrType">Initial value of AgeOrType.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Ticket CreateTicket(int ID, string price, string description, string type, string ageOrType)
        {
            Ticket ticket = new Ticket();
            ticket.id = ID;
            ticket.Price = price;
            ticket.Description = description;
            ticket.Type = type;
            ticket.AgeOrType = ageOrType;
            return ticket;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                this._Price = value;
                this.OnPriceChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Price;
        partial void OnPriceChanging(string value);
        partial void OnPriceChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Game_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Game_id
        {
            get
            {
                return this._Game_id;
            }
            set
            {
                this.OnGame_idChanging(value);
                this._Game_id = value;
                this.OnGame_idChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Game_id;
        partial void OnGame_idChanging(global::System.Nullable<int> value);
        partial void OnGame_idChanged();
        /// <summary>
        /// There are no comments for Property AgeOrType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AgeOrType
        {
            get
            {
                return this._AgeOrType;
            }
            set
            {
                this.OnAgeOrTypeChanging(value);
                this._AgeOrType = value;
                this.OnAgeOrTypeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AgeOrType;
        partial void OnAgeOrTypeChanging(string value);
        partial void OnAgeOrTypeChanged();
        /// <summary>
        /// There are no comments for Game in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Game Game
        {
            get
            {
                return this._Game;
            }
            set
            {
                this._Game = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Game _Game;
    }
    /// <summary>
    /// There are no comments for CrusadersModel.NewsEntity in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class NewsEntity
    {
        /// <summary>
        /// Create a new NewsEntity object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="image">Initial value of Image.</param>
        /// <param name="content">Initial value of Content.</param>
        /// <param name="title">Initial value of Title.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static NewsEntity CreateNewsEntity(int ID, string image, string content, string title)
        {
            NewsEntity newsEntity = new NewsEntity();
            newsEntity.Id = ID;
            newsEntity.Image = image;
            newsEntity.Content = content;
            newsEntity.Title = title;
            return newsEntity;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Image in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Image
        {
            get
            {
                return this._Image;
            }
            set
            {
                this.OnImageChanging(value);
                this._Image = value;
                this.OnImageChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Image;
        partial void OnImageChanging(string value);
        partial void OnImageChanged();
        /// <summary>
        /// There are no comments for Property Content in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Content
        {
            get
            {
                return this._Content;
            }
            set
            {
                this.OnContentChanging(value);
                this._Content = value;
                this.OnContentChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Content;
        partial void OnContentChanging(string value);
        partial void OnContentChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
    }
}
